# Top-level settings (common to all projects)
[GLOBAL]
NGSPICE_EXE_STR = "/usr/bin/ngspice"
NETLISTS_DIR_STR = "netlists"             # relative to proj dir, where netlists will be stored
RESULTS_DIR_STR = "sim_results"           # rel to proj dir, where sim results will be stored
SIM_TRANSCRIPT_STR = "sim_transcript.log" # filename for ngspice simulation transcripts

# Section 1-04-01 Dividers
[SEC_1_04_01]
PROJ_PATH_STR = "/workspaces/py4spice/circuits/sec_1_04_01_dividers"

# Section 1-04-02 Linear Regulator
[SEC_1_04_02]
PROJ_PATH_STR = "/workspaces/py4spice/circuits/sec_1_04_02_lin_reg"

# Section 1-04-04 Linear Regulator
[SEC_1_04_04]
PROJ_PATH_STR = "/workspaces/py4spice/circuits/sec_1_04_04_lin_reg"

# Section simple_rc
[SIMPLE_RC]
PROJ_PATH_STR = "/workspaces/py4spice/circuits/simple_rc"
